route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'webhook-dingtalk'

receivers:
  - name: 'webhook-dingtalk'
    webhook_configs:
      - url: 'http://192.168.178.40:8060/dingtalk/webhook2/send'

#inhibit_rules:
#  - source_match:
#      severity: 'critical'
#    target_match:
#      severity: 'warning'
#    equal: ['alertname', 'dev', 'instance']
